# 允许远程连接
bind 0.0.0.0
protected-mode no

# RDB持久化配置（与当前配置一致）
save 3600 1
save 300 100
save 60 10000
dir /data  # 数据存储目录
dbfilename dump.rdb

# 可选：启用AOF持久化（如需更高可靠性）
appendonly yes  # 保持关闭或改为yes
appendfilename "appendonly.aof"
appendfsync everysec

# 可选：设置密码dd
# requirepass yourpassword
